title: coolomina.dev
description: This is me!
author: Alejandro Colomina
github: https://github.com/Coolomina
about: "I'm a SRE (Super Rad Engineer) at Flywire"
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/coolomina"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/coolomina/"
    - icon: fa-github
      link: "https://github.com/Coolomina"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://coolomina.dev"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - docker-compose.yml
  - Dockerfile
